# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=b16b61c2ee
# 
# 

# ********RoostGPT********
Feature: Create a new country

  Background:
    * def urlBase = karate.properties['n']
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Test POST /country endpoint with valid payload
    Given path 'country'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    And request
      """
      {
        "name": "<name>",
        "code": "<code>",
        "currencies": <currencies>,
        "default_currency": "<default_currency>",
        "is_active": <is_active>
      }
      """
    When method POST
    Then status 201
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data.id == '#number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match response.data.currencies == '#array'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_post.csv') |

  Scenario: Test POST /country endpoint with missing required fields
    Given path 'country'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "code": "IND"
      }
      """
    When method POST
    Then assert responseStatus != 201
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Test POST /country endpoint with invalid payload data type
    Given path 'country'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "name": 12345,
        "code": "IND",
        "currencies": ["INR", "USD"],
        "default_currency": "INR",
        "is_active": "true"
      }
      """
    When method POST
    Then assert responseStatus != 201
    And match response.error.code == '#number'
    And match response.error.message == '#string'
