# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=9f2a876166
# 
# 

# ********RoostGPT********
Feature: Validate the Country API functionality

  Background:
    * def urlBase = karate.properties['n']
    * url urlBase
    * configure headers =
      """
      { 
        "Accept": "application/json", 
        "app-identifier": "#(processEnvironment.APP_IDENTIFIER)",
        "customer-secret-key": "#(processEnvironment.CUSTOMER_SECRET_KEY)" 
      }
      """

  Scenario Outline: Validate successful response for country fetch by ID
    Given path '/country/<id>'
    When method GET
    Then status 200
    And match response.status == 'success'
    And match response.message == 'Data fetched successfully'
    And match response.data.country.id == '#number'
    And match response.data.country.name == '#? _ == null || typeof _ == "string"'
    And match response.data.country.code == '#string'
    And match response.data.country.default_currency == '#string'
    And match response.data.country.is_active == '#number'
    And match response.data.country.app_id == '#number'
    And match response.data.country.customer_id == '#number'
    And match response.data.country.created_by == '#number'
    And match response.data.country.updated_by == '#number'
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'
    And match response.data.country.currencies == '#[string]'

    Examples:
      | read('country_id_get.csv') |

  Scenario: Validate error response when ID is missing
    Given path '/country'
    When method GET
    Then status != 200
    And assert karate.sizeOf(response.error_info) >= 0

  Scenario Outline: Validate error response for invalid ID
    Given path '/country/<id>'
    When method GET
    Then status != 200
    And assert karate.sizeOf(response.error_info) >= 0

    Examples:
      | id     |
      |     -1 |
      | 'null' |
      |      0 |
