# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=6873c73aa2
# 
# 

# ********RoostGPT********
Feature: Create Country API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * def authToken = karate.properties['BEARER_AUTH']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    * def appIdentifier = karate.properties['APP_IDENTIFIER']
    * def customerSecretKey = karate.properties['CUSTOMER_SECRET_KEY']

  Scenario Outline: Verify Create Country API with valid payload and headers
    Given path 'country'
    And method POST
    And request
      """
      {
        "name": "<name>",
        "code": "<code>",
        "currencies": <currencies>,
        "default_currency": "<default_currency>",
        "is_active": <is_active>
      }
      """
    And headers
      """
      { 
        "app-identifier": "#(appIdentifier)", 
        "customer-secret-key": "#(customerSecretKey)" 
      }
      """
    When status == 201
    Then match response.status == 'success'
    And match response.message == 'Country created successfully'
    And match response.data.id == '#number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#regex ^.*$'
    And match response.data.updated_at == '#regex ^.*$'
    And match response.data.currencies == '#[]'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | name     | code  | currencies             | default_currency | is_active |
      | 'INDIA'  | 'IND' | ['INR', 'USD', 'EURO'] | 'INR'            |         1 |
      | 'USA'    | 'USA' | ['USD', 'EURO']        | 'USD'            |         1 |
      | 'FRANCE' | 'FRA' | ['EURO']               | 'EURO'           |         1 |
