# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_get for http method type GET 
# RoostTestHash=3d9e7cb5d1
# 
# 

# ********RoostGPT********
Feature: Country API Testing

  Background:
    """
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = {
        'Accept': 'application/json',
        'app-identifier': '{{$processEnvironment.APP_IDENTIFIER}}',
        'customer-secret-key': '{{$processEnvironment.CUSTOMER_SECRET_KEY}}'
      }
    """
  
  Scenario: Verify successful response for GET /country
    Given path 'country'
    When method GET
    Then status 200
    And match response == '#object'
    And match response.status == '#string'
    And match response.status == 'success'
    And match response.message == '#string'
    And match response.message == 'Data fetched successfully'
    And match response.data == '#object'
    And match response.data.countries == '#array'
    And match each response.data.countries[*].id == '#number'
    And match each response.data.countries[*].name == '#? _ == null || typeof _ == "string"'
    And match each response.data.countries[*].code == '#string'
    And match each response.data.countries[*].default_currency == '#string'
    And match each response.data.countries[*].is_active == '#number'
    And match each response.data.countries[*].app_id == '#number'
    And match each response.data.countries[*].customer_id == '#number'
    And match each response.data.countries[*].created_by == '#number'
    And match each response.data.countries[*].updated_by == '#number'
    And match each response.data.countries[*].created_at == '#string'
    And match each response.data.countries[*].updated_at == '#string'
    And match each response.data.countries[*].currencies == '#array'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

  Scenario Outline: Testing error cases for Customer Secret Key Header
    Given path 'country'
    """
    * configure headers = {
        'Accept': 'application/json',
        'app-identifier': '{{$processEnvironment.APP_IDENTIFIER}}',
        'customer-secret-key': '<key>'
      }
    """
    When method GET
    Then assert responseStatus != 200
    And match response == '#object'
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | key                      |
      | ['INVALID_SECRET_KEY']   |
      | ['null']                 |
      | ['\' \'']                |

  Scenario Outline: Testing error cases for App Identifier Header
    Given path 'country'
    """
    * configure headers = {
        'Accept': 'application/json',
        'app-identifier': '<key>',
        'customer-secret-key': '{{$processEnvironment.CUSTOMER_SECRET_KEY}}'
      }
    """
    When method GET
    Then assert responseStatus != 200
    And match response == '#object'
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | key                      |
      | ['INVALID_IDENTIFIER']   |
      | ['null']                 |
      | ['\' \'']                |
