# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_put for http method type PUT 
# RoostTestHash=e5eb5af926
# 
# 

# ********RoostGPT********
Feature: Update Country by ID
In order to update a country by its ID
As a user of the Country API
I want to send a PUT request to the /country/{id} endpoint

  Background:
    * def urlBase = karate.properties['n']
    * url urlBase
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', 'Accept': 'application/json' }

  Scenario Outline: Validate successful update of country by ID
    Given path 'country', <id>
    And headers { 'app-identifier': '<app_identifier>', 'customer-secret-key': '<customer_secret_key>' }
    And request
      """
      {
          "name": "<name>",
          "code": "<code>",
          "currencies": <currencies>,
          "default_currency": "<default_currency>",
          "is_active": <is_active>
      }
      """
    When method PUT
    Then status 200
    And match response.status == 'success'
    And match response.message == 'Country updated successfully'
    And match response.data.id == <id>
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match response.data.currencies contains '#[]'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_id_put.csv') |

  Scenario: Validate unauthorized access when no token is provided
    Given path 'country', 32
    And headers { 'app-identifier': 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d', 'customer-secret-key': '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe' }
    And request
      """
      {
          "name": "INDIA",
          "code": "IND",
          "currencies": ["INR", "USD", "EURO"],
          "default_currency": "INR",
          "is_active": 1
      }
      """
    When method PUT
    Then assert responseStatus != 200

  Scenario Outline: Validate error response when mandatory headers are missing
    Given path 'country', <id>
    And headers { Authorization: '#(authToken)' }
    And request
      """
      {
          "name": "<name>",
          "code": "<code>",
          "currencies": <currencies>,
          "default_currency": "<default_currency>",
          "is_active": <is_active>
      }
      """
    When method PUT
    Then assert responseStatus != 200
    And match response.error.code == '#string'
    And match response.error.message == '#string'

    Examples:
      | id | name    | code  | currencies             | default_currency | is_active |
      | 32 | 'INDIA' | 'IND' | ['INR', 'USD', 'EURO'] | 'INR'            |         1 |
      | 32 | 'USA'   | 'USA' | ['USD', 'CAD']         | 'USD'            |         0 |
