# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=9f2a876166
# 
# 

# ********RoostGPT********
Feature: Get Country by ID API

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = true
    * header Accept = 'application/json'

  Scenario Outline: Verify successful response for valid country ID
    Given path 'country/<id>'
    And headers """
      {
        'app-identifier': '<app_identifier>', 
        'customer-secret-key': '<customer_secret_key>'
      }
    """
    When method GET
    Then status 200
    And match response.status == 'success'
    And match response.message == 'Data fetched successfully'
    And match response.data.country.id == <id>
    And match response.data.country.name == '#? _ == null || typeof _ == "string"'
    And match response.data.country.code == '#string'
    And match response.data.country.default_currency == '#string'
    And match response.data.country.is_active == '#number'
    And match response.data.country.app_id == '#number'
    And match response.data.country.customer_id == '#number'
    And match response.data.country.created_by == '#number'
    And match response.data.country.updated_by == '#number'
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'
    And match response.data.country.currencies == '#array'
    And match each response.data.country.currencies[*] == '#string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | id | app_identifier                                                 | customer_secret_key                                            |
      | 32 | ['d645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'] | ['12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'] |

  Scenario Outline: Verify error response for invalid country ID
    Given path 'country/<id>'
    And headers """
      {
        'app-identifier': '<app_identifier>', 
        'customer-secret-key': '<customer_secret_key>'
      }
    """
    When method GET
    Then assert responseStatus != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | id    | app_identifier                                                 | customer_secret_key                                            |
      | 99999 | ['d645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'] | ['12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'] |

  Scenario Outline: Verify missing required headers
    Given path 'country/<id>'
    And headers """
      {
        'app-identifier': '',
        'customer-secret-key': ''
      }
    """
    When method GET
    Then assert responseStatus != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | id |
      | 32 |

  Scenario Outline: Validate response attributes against data type constraints
    Given path 'country/<id>'
    And headers """
      {
        'app-identifier': '<app_identifier>', 
        'customer-secret-key': '<customer_secret_key>'
      }
    """
    When method GET
    Then status 200
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data.country.id == '#number'
    And match response.data.country.currencies == '#array'

    Examples:
      | id | app_identifier                                                 | customer_secret_key                                            |
      | 32 | ['d645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'] | ['12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'] |
