# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=6873c73aa2
# 
# 

# ********RoostGPT********
Feature: Create Country API Tests

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }

  Scenario Outline: Validate Create Country API Response
    Given url baseURL + '/country'
    And header app-identifier = <app_identifier>
    And header customer-secret-key = <customer_secret_key>
    And request
      """
      {
        "name": "<name>",
        "code": "<code>",
        "currencies": <currencies>,
        "default_currency": "<default_currency>",
        "is_active": <is_active>
      }
      """
    When method POST
    Then status <response_status>
    And match response.status == "<expected_status>"
    And match response.message == '#string'
    And match response.data.id == '#number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match each response.data.currencies[*] == '#string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | app_identifier                                                 | customer_secret_key                                            | name    | code  | currencies             | default_currency | is_active | response_status | expected_status |
      | 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d' | '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe' | 'INDIA' | 'IND' | ['INR', 'USD', 'EURO'] | 'INR'            |         1 |             201 | 'success'       |

  Scenario: Validate Incorrect App Identifier and Access Denied
    Given url baseURL + '/country'
    And header app-identifier = 'INVALID_IDENTIFIER'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "name": "INDIA",
        "code": "IND",
        "currencies": ["INR", "USD", "EURO"],
        "default_currency": "INR",
        "is_active": 1
      }
      """
    When method POST
    Then status 401
    And match response.error == '#string'

  Scenario: Validate Missing Required Fields
    Given url baseURL + '/country'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "name": null,
        "code": "IND",
        "currencies": [],
        "default_currency": "",
        "is_active": 1
      }
      """
    When method POST
    Then status 400
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Validate Invalid Data Types
    Given url baseURL + '/country'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "name": 1234,
        "code": true,
        "currencies": [123, 456],
        "default_currency": false,
        "is_active": "string_type"
      }
      """
    When method POST
    Then status 400
    And match response.error.code == '#number'
    And match response.error.message == '#string'

  Scenario: Validate Server Error
    Given url baseURL + '/country'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
        "name": "INDIA",
        "code": "IND",
        "currencies": ["INR", "USD", "EURO"],
        "default_currency": "INR",
        "is_active": 1
      }
      """
    When method POST
    Then status >= 500
    And match response.error.code == '#number'
    And match response.error.message == '#string'
