# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=5c040001f7
# 
# 

# ********RoostGPT********
Feature: Delete country by ID API endpoint tests

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = true
    * header Accept = 'application/json'
    * header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    * header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'

  Scenario Outline: Delete country by ID with valid parameters
    Given path '/country/' + <id>
    When method DELETE
    Then status 200
    And match response ==
      """
      {
        "status": "success",
        "message": "Country deleted successfully",
        "error_info": null
      }
      """

    Examples:
      | read('country_id_delete.csv') |

  Scenario: Delete country by ID with invalid ID
    Given path '/country/999999'
    When method DELETE
    Then status != 200
