# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_get for http method type GET 
# RoostTestHash=3d9e7cb5d1
# 
# 

# ********RoostGPT********
Feature: Test suite for /country endpoint

  Background:
    """
    {
      "urlBase": karate.properties['n'], 
      "headers": {
        "Accept": "application/json", 
        "app-identifier": '{{$processEnvironment.AUTH_TOKEN}}', 
        "customer-secret-key": '{{$processEnvironment.SECRET_KEY}}'
      }
    }
    """

    * def urlBase = karate.properties['n']
    * url urlBase
    * configure headers = { "Accept": "application/json", "app-identifier": '{{$processEnvironment.AUTH_TOKEN}}', "customer-secret-key": '{{$processEnvironment.SECRET_KEY}}' }

  Scenario: Validate successful response for GET /country
    Given path 'country'
    When method GET
    Then status 200
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.data.countries == '#array'
    And match each response.data.countries[*].id == '#number'
    And match each response.data.countries[*].name == '#string'
    And match each response.data.countries[*].code == '#string'
    And match each response.data.countries[*].default_currency == '#string'
    And match each response.data.countries[*].is_active == '#number'
    And match each response.data.countries[*].app_id == '#number'
    And match each response.data.countries[*].customer_id == '#number'
    And match each response.data.countries[*].created_by == '#number'
    And match each response.data.countries[*].updated_by == '#number'
    And match each response.data.countries[*].created_at == '#string'
    And match each response.data.countries[*].updated_at == '#string'
    And match each response.data.countries[*].currencies == '#array'
    And match response.error_info == '#string'

  Scenario Outline: Validate response with invalid/missing headers for GET /country
    Given headers { "app-identifier": "<app_identifier>", "customer-secret-key": "<customer_secret_key>" }
    Given path 'country'
    When method GET
    Then status #{assert karate.sizeForSub(
