# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_put for http method type PUT 
# RoostTestHash=e5eb5af926
# 
# 

# ********RoostGPT********
Feature: Update country by ID
    This feature tests the /country/{id} endpoint for updating country details using various scenarios.

  Background:
    * def baseURL = karate.properties['SAMPLE_API_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * def authToken = 'Bearer ' + karate.properties['AUTH_TOKEN']
    * configure headers = { Authorization: '#(authToken)', Accept: 'application/json' }
    * configure report = false

  Scenario Outline: Update country by ID with valid payload
    Given path 'country/<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    And request
      """
      {
          "name": "<name>",
          "code": "<code>",
          "currencies": <currencies>,
          "default_currency": "<default_currency>",
          "is_active": <is_active>
      }
      """
    When method PUT
    Then status 200
    And match response.status == 'success'
    And match response.message == 'Country updated successfully'
    And match response.data.id == '#number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#regex ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z$'
    And match response.data.updated_at == '#regex ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}Z$'
    And match response.data.currencies == '#[]'
    And match response.data.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_id_put.csv') |
