# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=9f2a876166
# 
# 

# ********RoostGPT********
Feature: Get Country by ID API

  Background:
    """
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'
    * header app-identifier = karate.properties.APP_IDENTIFIER
    * header customer-secret-key = karate.properties.CUSTOMER_SECRET_KEY
    """

  Scenario Outline: Valid case - Fetch country details with valid ID
    Given path 'country/<id>'
    When method GET
    Then status 200
    And match response.status == 'success'
    And match response.message == '#string'
    And match response.data.country.id == '#number'
    And match response.data.country.name == '#? _ == null || typeof _ == "string"'
    And match response.data.country.code == '#string'
    And match response.data.country.default_currency == '#string'
    And match response.data.country.is_active == '#number'
    And match response.data.country.app_id == '#number'
    And match response.data.country.customer_id == '#number'
    And match response.data.country.created_by == '#number'
    And match response.data.country.updated_by == '#number'
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'
    And match response.data.country.currencies == '#array'
    And match each response.data.country.currencies[*] == '#string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | id |
      | 32 |
      | 45 |
      | 99 |

  Scenario Outline: Invalid case - Invalid country ID
    Given path 'country/<id>'
    When method GET
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | id          |
      | -1          |
      | 99999999999 |
      | 0           |

  Scenario Outline: Invalid case - Invalid headers
    Given header app-identifier = '<app-identifier>'
    Given header customer-secret-key = '<customer-secret-key>'
    Given path 'country/<id>'
    When method GET
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | id | app-identifier                           | customer-secret-key                      |
      | 32 | ''                                       | ''                                       |
      | 45 | 'invalid-app-id'                         | 'invalid-secret-key'                     |
      | 99 | 'd645d2b40811f5672c93794d8622da45588f32' | '12546580645c21b8a3529680f455f715b6b682' |

  Scenario: Valid case - Verify response structure for currencies and timestamps
    Given path 'country/32'
    When method GET
    Then status 200
    And match response.data.country.currencies == '#array'
    And assert karate.sizeOf(response.data.country.currencies) >= 3
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'
    And match response.data.country.created_at CONTAINS 'T'
    And match response.data.country.updated_at CONTAINS 'T'
