# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=5c040001f7
# 
# 

# ********RoostGPT********
Feature: Delete country by ID API endpoint tests

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Validate successful deletion of country by ID
    Given path 'country/' + '<id>'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    When method DELETE
    Then status 200
    And match response.status == '#string'
    And match response.message == '#string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_id_delete.csv') |
