# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country_post for http method type POST 
# RoostTestHash=6873c73aa2
# 
# 

# ********RoostGPT********
Feature: Create new country API validations

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'

  Scenario Outline: Validate POST /country response for valid inputs
    Given path 'country'
    And header app-identifier = '<app_identifier>'
    And header customer-secret-key = '<customer_secret_key>'
    And request
      """
      {
          "name": "<name>",
          "code": "<code>",
          "currencies": <currencies>,
          "default_currency": "<default_currency>",
          "is_active": <is_active>
      }
      """
    When method POST
    Then status 201
    And match response.status == 'success'
    And match response.message == '##string'
    And match response.data.id == '#number'
    And match response.data.name == '#? _ == null || typeof _ == "string"'
    And match response.data.code == '#string'
    And match response.data.default_currency == '#string'
    And match response.data.is_active == '#number'
    And match response.data.app_id == '#number'
    And match response.data.customer_id == '#number'
    And match response.data.created_by == '#number'
    And match response.data.updated_by == '#number'
    And match response.data.created_at == '#string'
    And match response.data.updated_at == '#string'
    And match response.data.currencies == '#[] custom'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_post.csv') |

  Scenario: Validate error handling for missing headers in POST /country
    Given path 'country'
    And request
      """
      {
          "name": "USA",
          "code": "USA",
          "currencies": ["USD", "INR"],
          "default_currency": "USD",
          "is_active": 1
      }
      """
    When method POST
    Then status != 201
    And match response.error.code == '#number'
    And match response.error.message == '##string'

  Scenario: Validate response error for missing required fields
    Given path 'country'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    And request
      """
      {
          "name": "",
          "code": null,
          "currencies": [],
          "default_currency": "",
          "is_active": null
      }
      """
    When method POST
    Then status != 201
    And match response.error.code == '#number'
    And match response.error.message == '##string'
