
// ********RoostGPT********
/*

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=9f2a876166
# 
# 

roost_feedback [21/07/2025, 5:16:42 PM]:add the comments to the test\n
*/

// ********RoostGPT********

Feature: Validate Get Country by ID API

Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'

Scenario Outline: Validate response for successful Get Country by ID
    # Verify the response structure and ensure all required fields are returned correctly
    # Check that the API returns status 200
    Given path 'country', <id>
    # Validate required headers
    And header app-identifier = <app_identifier>
    And header customer-secret-key = <customer_secret_key>
    # Execute GET method and validate response
    When method GET
    Then status 200
    And match response ==
      """
      {
        status: '#string',
        message: '#string',
        data: {
          country: {
            id: '#number',
            name: '#? _ == null || typeof _ == "string"',
            code: '#string',
            default_currency: '#string',
            is_active: '#number',
            app_id: '#number',
            customer_id: '#number',
            created_by: '#number',
            updated_by: '#number',
            created_at: '#string',
            updated_at: '#string',
            currencies: '#array'
          }
        },
        error_info: '#? _ == null || typeof _ == "string"'
      }
      """
    # Ensure the number of currencies is at least 1
    And assert karate.sizeOf(response.data.country.currencies) >= 1
    # Verify response contains created_at and updated_at fields
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'

    Examples:
      | read('country_id_get.csv') |

Scenario: Validate error response when required headers are missing
    # Check the API returns appropriate error response when headers are missing
    # Validate response contains error details
    Given path 'country', 32
    And header app-identifier = null
    And header customer-secret-key = null
    When method GET
    Then assert responseStatus != 200
    And match response ==
      """
      {
        error: {
          code: '#string',
          message: '#string'
        }
      }
      """

Scenario: Validate response when path parameter is invalid
    # Ensure the API handles invalid path parameters gracefully
    # Verify error message structure
    Given path 'country', 'invalid_id'
    And header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    And header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    When method GET
    Then assert responseStatus != 200
    And match response ==
      """
      {
        error: {
          code: '#string',
          message: '#string'
        }
      }
      """
