# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=ff433d7857
# 
# 

# ********RoostGPT********
Feature: Test Nobel Prize Laureates API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Accept: 'application/json' }

  Scenario Outline: Verify successful response for GET /2.1/laureates with query parameters
    Given path '2.1/laureates'
    And params { 'offset': <offset>, 'limit': <limit>, 'gender': <gender>, 'birthCity': <birthCity>, 'nobelPrizeCategory': <nobelPrizeCategory> }
    When method GET
    Then status 200
    And match response.laureates == '#? _ == null || typeof _ == "array"'
    And match each response.laureates[*].id == '#number'
    And match response.meta.offset == '#number'
    And match response.meta.limit == '#number'
    And match response.meta.gender == '##string'

    Examples:
      | read('laureates_get.csv') |

  Scenario: Verify response when accessing laureates without query parameters
    Given path '2.1/laureates'
    When method GET
    Then status 200
    And match response.laureates == '#? _ == null || typeof _ == "array"'
    And match response.meta.offset == '#? _ == null || typeof _ == "number"'
    And match response.meta.limit == '#? _ == null || typeof _ == "number"'

  Scenario Outline: Verify response for GET /2.1/laureates with invalid query parameter values
    Given path '2.1/laureates'
    And params { 'offset': <offset>, 'limit': <limit>, 'gender': <gender>, 'birthCity': <birthCity>, 'nobelPrizeCategory': <nobelPrizeCategory> }
    When method GET
    Then status != 200
    And assert response.error.code == '##string'
    And assert response.error.message == '##string'

    Examples:
      | offset | limit | gender  | birthCity     | nobelPrizeCategory |
      |      0 |     5 | null    | null          | 'InvalidCategory'  |
      | null   | null  | 'alien' | 'UnknownCity' | null               |

  Scenario: Verify response for POST method is not allowed
    Given path '2.1/laureates'
    When method POST
    Then status != 200
    And assert responseStatus == 405

  Scenario Outline: Verify error handling for invalid range dates in query parameters
    Given path '2.1/laureates'
    And params { 'birthDate': <birthDate>, 'birthDateTo': <birthDateTo> }
    When method GET
    Then status != 200
    And assert response.error.code == '##string'
    And assert response.error.message == '##string'

    Examples:
      | birthDate | birthDateTo  |
      | 'invalid' | 'invalid'    |
      | null      | '2024-01-01' |

  Scenario: Verify response schema for 200 OK with full nested properties in laureates
    Given path '2.1/laureates'
    And params { 'offset': 1, 'limit': 1 }
    When method GET
    Then status 200
    And match response.laureates[*].id == '#number'
    And match response.laureates[*].laureateIfPerson.knownName.en == '##string'
    And match response.laureates[*].laureateIfPerson.birth.place.city.en == '##string'
    And match response.laureates[*].laureateIfPerson.death.place.countryNow.sameAs == '#? typeof _ == "array"'
    And match response.laureates[*].nobelPrizes[*].awardYear == '#number'
    And match response.laureates[*].nobelPrizes[*].affiliations[*].name.en == '##string'
