# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: Get Nobel Prize Laureate Information by ID

  Background:
    """
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { "Accept": "application/json" }
    """

  Scenario Outline: Validate successful retrieval of Nobel Prize Laureate information by ID
    Given path '/2.1/laureate/<laureateID>'
    When method GET
    Then status 200
    And match response.laureate.id == '#number'
    And match response.laureate.id > 0
    And match response.laureate.laureateIfPerson.knownName.en == '##string'
    And match response.laureate.laureateIfPerson.fullName.en == '##string'
    And match response.laureate.laureateIfPerson.penname == '#? _ == null || typeof _ == "string"'
    And match response.laureate.laureateIfPerson.gender == '##string'
    And match response.laureate.laureateIfPerson.birth.date == '##string'
    And match response.laureate.laureateIfPerson.birth.place.city.en == '##string'
    And match response.laureate.laureateIfPerson.birth.place.country.en == '##string'
    And match response.laureate.laureateIfPerson.death.date == '#? _ == null || typeof _ == "string"'
    And match response.laureate.laureateIfPerson.death.place.city.en == '#? _ == null || typeof _ == "string"'
    And match response.laureate.laureateIfPerson.death.place.country.en == '#? _ == null || typeof _ == "string"'
    And match response.laureate.laureateIfOrg.headquarters.city.en == '#? _ == null || typeof _ == "string"'
    And match response.laureate.wikidata.id == '#? _ == null || typeof _ == "string"'
    And match response.laureate.sameAs == [ '#string' ]
    And match response.laureate.links == [ '#string' ]
    And match response.laureate.nobelPrizes == [ '#number' ]

    Examples:
      | laureateID |
      | "1"        |
      | "2"        |
      | "3"        |
      | "4"        |

  Scenario: Validate graceful error handling for incorrect Laureate ID
    Given path '/2.1/laureate/999999'
    When method GET
    Then status 404
    And match response == null
