# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=ff433d7857
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Laureates API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'

  Scenario: Validate successful GET request with query parameters
    Given path '/2.1/laureates'
    And param offset = 1
    And param limit = 10
    When method GET
    Then status 200
    And match response.laureates == "#[]"
    And match response.meta.offset == "#number"
    And match response.meta.limit == "#number"
    And match response.meta.count == "#number"
    And match response.links == "#[]"

  Scenario Outline: Validate successful GET request with optional query parameters
    Given path '/2.1/laureates'
    And param offset = <offset>
    And param limit = <limit>
    And param sort = <sort>
    And param ID = <ID>
    And param name = <name>
    And param gender = <gender>
    When method GET
    Then status 200
    And match response.laureates == "#[]"

    Examples:
      | read('laureates_get.csv') |

  Scenario: Validate unsuccessful GET request with malformed query parameters
    Given path '/2.1/laureates'
    And param offset = -1
    And param limit = -10
    When method GET
    Then status 400
    And match response.code == "#string"
    And match response.message == "#string"

  Scenario: Validate resource not found for GET request
    Given path '/2.1/laureates'
    And param ID = 999999
    When method GET
    Then status 404
    And match response.code == "#string"
    And match response.message == "#string"

  Scenario Outline: Validate unprocessable entity for incorrect query parameters combination
    Given path '/2.1/laureates'
    And param birthDate = <invalid_date>
    And param birthDateTo = <invalid_date_range>
    When method GET
    Then status 422
    And match response.code == "#string"
    And match response.message == "#string"

    Examples:
      | invalid_date | invalid_date_range |
      | 'invalid'    | 'invalid_range'    |

  Scenario: Validate properties of laureates array on successful response
    Given path '/2.1/laureates'
    When method GET
    Then status 200
    And match response.laureates[0].id == "#number"
    And match response.laureates[0].laureateIfPerson.knownName.en == "#string"
    And match response.laureates[0].nobelPrizes[0].awardYear == "#number"
    And match response.laureates[0].sameAs == "#[]"

  Scenario: Validate response meta information structure
    Given path '/2.1/laureates'
    And param offset = 1
    And param limit = 10
    When method GET
    Then status 200
    And match response.meta.offset == "#number"
    And match response.meta.limit == "#number"
    And match response.meta.sort == "#string"

  Scenario Outline: Validate response with different genders
    Given path '/2.1/laureates'
    And param gender = <gender>
    When method GET
    Then status 200
    And match response.laureates == "#[]"

    Examples:
      | read('laureates_get.csv') |

  Scenario: Validate response links structure
    Given path '/2.1/laureates'
    When method GET
    Then status 200
    And match response.links[0].self == "#string"
    And match response.links[0].first == "#string"
    And match response.links[0].prev == "#string"
    And match response.links[0].next == "#string"
    And match response.links[0].last == "#string"
