# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureate/{laureateID}_get for http method type GET 
# RoostTestHash=e702c0f931
# 
# 

# ********RoostGPT********
Feature: Validate API for Nobel Prize Laureate using laureateID

  Background:
    """
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Accept: 'application/json', Authorization: '{{$processEnvironment.AUTH_TOKEN}}' }
    """

  Scenario Outline: Validate Laureate API with valid laureateID
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 200
    And match response.laureate.id == '#number'
    And match response.laureate.id >= 1
    And match response.laureate.laureateIfPerson.knownName.en == '#string'
    And match response.laureate.laureateIfOrg.orgName.en == '#string'
    And match response.laureate.laureateIfOrg.headquarters.city.en == '#string'
    And match response.laureate.laureateIfPerson.birth.date == '#string'
    And match response.laureate.laureateIfPerson.birth.place.city.en == '#string'
    And match response.laureate.laureateIfPerson.death.date == '#string'
    And match response.laureate.laureateIfPerson.death.place.city.en == '#string'
    And match response.laureate.wikidata.id == '#string'
    And match response.laureate.wikidata.url == '#string'
    And match response.laureate.sameAs == '[]'
    And match each response.laureate.nobelPrizes[*].awardYear == '#number'
    And match response.laureate.links == '[]'

    Examples:
      | laureateID |
      |    '456'   |
      |    '123'   |
      |    '789'   |

  Scenario: Validate Laureate API response for malformed syntax (Bad Request)
    Given path '2.1/laureate/'
    When method GET
    Then status 400
    And match response.code == '400'
    And match response.message == '#string'

  Scenario: Validate Laureate API response for Not Found
    Given path '2.1/laureate/-1'
    When method GET
    Then status 404
    And match response.code == '404'
    And match response.message == '#string'

  Scenario Outline: Validate Laureate API response for Unprocessable Entity
    Given path '2.1/laureate/<laureateID>'
    When method GET
    Then status 422
    And match response.code == '422'
    And match response.message == '#string'

    Examples:
      | laureateID |
      |  'invalid' |
      |     null   |
      |    '-100'  |
