# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /laureates_get for http method type GET 
# RoostTestHash=ff433d7857
# 
# 

# ********RoostGPT********
Feature: Validate Nobel Prize Laureates API

  Background:
    """
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = true
    * header Accept = 'application/json'
    """

  Scenario Outline: GET /2.1/laureates with valid parameters and query
    Given path '/2.1/laureates'
    And param offset = <offset>
    And param limit = <limit>
    And param name = <name>
    And param gender = <gender>
    When method GET
    Then status 200
    And match response.laureates == '#[]'
    And match each response.laureates[*].id == '#number'
    And match each response.laureates[*].laureateIfPerson.knownName.en == '#string'
    And match each response.laureates[*].laureateIfPerson.birth.date == '#? _ == null || typeof _ == "string"'
    And match response.meta.offset == '#number'
    And match response.meta.limit == '#number'

    Examples:
      | offset | limit | name      | gender     |
      | 1      | 10    | ['John']  | ['male']   |
      | 5      | 25    | ['Marie'] | ['female'] |

  Scenario: GET /2.1/laureates with invalid query parameters
    Given path '/2.1/laureates'
    And param offset = -1
    And param limit = 0
    When method GET
    Then status 400
    And match response.code == '#string'
    And match response.message == '#string'

  Scenario: Access non-existing laureates resource
    Given path '/2.1/laureates'
    And param ID = 999999
    When method GET
    Then status 404
    And match response.code == '#string'
    And match response.message == '#string'

  Scenario Outline: Unprocessable Entity response
    Given path '/2.1/laureates'
    And param birthDate = <birthDate>
    And param deathDateTo = <deathDateTo>
    When method GET
    Then status 422
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | birthDate           | deathDateTo       |
      | ['1900-01-01']      | ['2023-01-01']    |

  Scenario: Validate pagination and navigation links
    Given path '/2.1/laureates'
    And param offset = 1
    And param limit = 10
    When method GET
    Then status 200
    And match response.links.self == '#string'
    And match response.links.next == '#? _ == null || typeof _ == "string"'
    And match response.links.last == '#string'

  Scenario: Validate metadata in successful response
    Given path '/2.1/laureates'
    And param nobelPrizeYear = 2022
    And param nobelPrizeCategory = ['Physics']
    When method GET
    Then status 200
    And match response.meta.count == '#number'
    And match response.meta.nobelPrizeYear == '#number'
    And match response.meta.nobelPrizeCategory == '#string'
    And assert karate.sizeOf(response.laureates) >= 1
