# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Tests for Nobel Prize API endpoint

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers =
      """
      {
        "Accept": "application/json"
      }
      """

  Scenario Outline: Validate successful GET request for Nobel Prize by category and year
    Given path '/2.1/nobelPrize/<category>/<year>'
    When method GET
    Then status 200
    And match response.nobelPrize.awardYear == '#number'
    And match response.nobelPrize.category.en == '#string'
    And match response.nobelPrize.category.se == '#string'
    And match response.nobelPrize.categoryFullName.en == '#string'
    And match response.nobelPrize.categoryFullName.se == '#string'
    And match response.nobelPrize.dateAwarded == '#string'
    And match response.nobelPrize.prizeAmount == '#number'
    And match response.nobelPrize.prizeAmountAdjusted == '#number'
    And match response.nobelPrize.topMotivation.en == '#string'
    And match response.nobelPrize.topMotivation.se == '#string'
    And match response.nobelPrize.laureates == '#[]'
    And match each response.nobelPrize.laureates[*].id == '#number'
    And match each response.nobelPrize.laureates[*].name.en == '#string'
    And match each response.nobelPrize.laureates[*].name.se == '#string'
    And match each response.nobelPrize.laureates[*].portion == '#string'
    And match each response.nobelPrize.laureates[*].sortOrder == '#string'
    And match each response.nobelPrize.laureates[*].motivation.en == '#string'
    And match each response.nobelPrize.laureates[*].motivation.se == '#string'
    And match each response.nobelPrize.laureates[*].links == '#[]'
    And match each response.nobelPrize.laureates[*].links[*].rel == '#string'
    And match each response.nobelPrize.laureates[*].links[*].href == '#string'

    Examples:
      | read('nobelPrize_category_year_get.csv') |

  Scenario Outline: Validate unsuccessful GET request for bad input
    Given path '/2.1/nobelPrize/<category>/<year>'
    When method GET
    Then status != 200
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | category  | year  |
      | 'peace'   |  1800 |
      | 'unknown' |  2000 |
      | 'physics' | 12345 |

  Scenario: Validate response for 400 Bad Request
    Given path '/2.1/nobelPrize/invalid-category/1895'
    When method GET
    Then status 400
    And match response.code == '#string'
    And match response.message == '#string'

  Scenario: Validate response for 404 Not Found
    Given path '/2.1/nobelPrize/peace/1234'
    When method GET
    Then status 404
    And match response.code == '#string'
    And match response.message == '#string'

  Scenario: Validate response for 422 Unprocessable Entity
    Given path '/2.1/nobelPrize/physics/-123'
    When method GET
    Then status 422
    And match response.code == '#string'
    And match response.message == '#string'
