# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Test Nobel Prize RESTful API for retrieving specific Nobel Prize information

  Background:
    """
    {
      "urlBase": karate.properties['URL_BASE'],
      "headers": {
        "Accept": "application/json",
        "Authorization": "{{$processEnvironment.AUTH_TOKEN}}"
      }
    }
    """

  Scenario Outline: Validate successful response for Nobel Prize retrieval
    Given path '2.1/nobelPrize', <category>, <year>
    When method GET
    Then status 200
    And match response.nobelPrize.awardYear == '#number'
    And match response.nobelPrize.category.en == '#string'
    And match response.nobelPrize.category.se == '#string'
    And match response.nobelPrize.categoryFullName.en == '#string'
    And match response.nobelPrize.categoryFullName.se == '#string'
    And match response.nobelPrize.dateAwarded == '#string'
    And match response.nobelPrize.dateAwarded == '#regex "\\d{4}-\\d{2}-\\d{2}"'
    And match response.nobelPrize.prizeAmount == '#number'
    And match response.nobelPrize.prizeAmountAdjusted == '#number'
    And match response.nobelPrize.topMotivation.en == '#string'
    And match response.nobelPrize.topMotivation.se == '#string'
    And match response.nobelPrize.laureates == '#array'
    And match each response.nobelPrize.laureates[*].id == '#number'
    And match each response.nobelPrize.laureates[*].name.en == '#string'
    And match each response.nobelPrize.laureates[*].name.se == '#string'
    And match each response.nobelPrize.laureates[*].portion == '#string'
    And match each response.nobelPrize.laureates[*].sortOrder == '#string'
    And match each response.nobelPrize.laureates[*].motivation.en == '#string'
    And match each response.nobelPrize.laureates[*].motivation.se == '#string'
    And match each response.nobelPrize.laureates[*].links[*].rel == '#string'
    And match each response.nobelPrize.laureates[*].links[*].href == '#string'
    And match each response.nobelPrize.laureates[*].links[*].action == '#string'
    And match each response.nobelPrize.laureates[*].links[*].types == '#string'

    Examples:
      | read('nobelPrize_category_year_get.csv') |

  Scenario Outline: Validate error response for malformed requests
    Given path '2.1/nobelPrize', <category>, <year>
    When method GET
    Then status != 200
    And match response.code == '#string'
    And match response.message == '#string'

    Examples:
      | category     | year |
      | 'unknown'    | 2018 |
      | 'literature' | 1899 |
      | 'medicine'   | 2050 |

  Scenario: Validate response for missing parameters
    Given path '2.1/nobelPrize', '', ''
    When method GET
    Then status != 200
    And match response.code == '#string'
    And match response.message == '#string'

  Scenario: Validate unsupported HTTP method
    Given path '2.1/nobelPrize', 'peace', 2021
    When method POST
    Then status != 200
    And match response.code == '#string'
    And match response.message == '#string'
