# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Nobel Prizes API Test Suite

  Background:
    """
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * configure headers = { Accept: 'application/json' }
    """

  Scenario Outline: Validate GET /2.1/nobelPrizes API with valid query parameters
    Given path '2.1/nobelPrizes'
    And param offset = <offset>
    And param limit = <limit>
    And param sort = <sort>
    And param nobelPrizeYear = <nobelPrizeYear>
    And param yearTo = <yearTo>
    And param nobelPrizeCategory = <nobelPrizeCategory>
    When method GET
    Then status 200
    And match response.nobelPrizes == '#[]'
    And match response.meta.offset == <offset>
    And match response.meta.limit == <limit>
    And match response.meta.nobelPrizeYear == '#? _ == null || _ == <nobelPrizeYear>'
    And match response.meta.yearTo == '#? _ == null || _ == <yearTo>'
    And match response.meta.nobelPrizeCategory == '#? _ == null || _ == <nobelPrizeCategory>'
    And match each response.nobelPrizes[*].awardYear == '#number'
    And match each response.nobelPrizes[*].category.en == '#string'
    And match each response.nobelPrizes[*].category.se == '#string'
    And match each response.nobelPrizes[*].categoryFullName.en == '#string'

    Examples:
      | offset | limit | sort   | nobelPrizeYear | yearTo | nobelPrizeCategory |
      | [5]    | [10]  | ['asc']|           [2020]| null   | ['chemistry']      |
      | [1]    | [2]   | ['desc']| null           | [2019] | null               |

  Scenario: Validate GET /2.1/nobelPrizes API with invalid query parameters
    Given path '2.1/nobelPrizes'
    And param offset = -1
    And param limit = -1
    And param nobelPrizeCategory = '@invalid'
    When method GET
    Then status 400
    And match response.code == '400'
    And match response.message == '#string'

  Scenario: Validate GET /2.1/nobelPrizes API not found resource
    Given path '2.1/nonExistentEndpoint'
    When method GET
    Then status 404
    And match response.code == '404'
    And match response.message == '#string'

  Scenario: Validate GET /2.1/nobelPrizes API for a semantic error
    Given path '2.1/nobelPrizes'
    And param offset = null
    And param limit = null
    When method GET
    Then status 422
    And match response.code == '422'
    And match response.message == '#string'

  Scenario Outline: Validate GET /2.1/nobelPrizes API response schema and data types
    Given path '2.1/nobelPrizes'
    And param offset = <offset>
    And param limit = <limit>
    When method GET
    Then status 200
    And match response == '#object'
    And match response.nobelPrizes == '#[]'
    And match response.meta.offset == '#number'
    And match response.meta.limit == '#number'
    And match response.meta.count == '#number'
    And match response.links == '#[]'
    And match each response.links[*].self == '#string'
    And match each response.links[*].next == '#string'

    Examples:
      | offset | limit |
      | [1]    | [20]  |
      | [3]    | [15]  |
