# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrizes_get for http method type GET 
# RoostTestHash=977dd819cb
# 
# 

# ********RoostGPT********
Feature: Karate tests for Nobel Prizes API

  Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = true
    * header Accept = 'application/json'

  Scenario: GET Nobel Prizes with all valid fields
    Given path '2.1/nobelPrizes'
    And param offset = 1
    And param limit = 5
    And param sort = 'year'
    And param nobelPrizeYear = 2020
    And param yearTo = 2021
    And param nobelPrizeCategory = 'phy'
    When method GET
    Then status 200
    And match response.nobelPrizes == '#[]'
    And match response.nobelPrizes[*].awardYear == '#number'
    And match response.nobelPrizes[*].category.en == '#string'
    """
    And match response.meta == {
      "offset": '#number',
      "limit": '#number',
      "nobelPrizeYear": '#number',
      "yearTo": '#number',
      "nobelPrizeCategory": '#string',
      "count": '#number'
    }
    """
    """
    And match response.links[*] == {
      "first": '#string',
      "last": '#string',
      "next": '#string'
    }
    """

  Scenario Outline: GET Nobel Prizes with dynamic parameters
    Given path '2.1/nobelPrizes'
    And param offset = <offset>
    And param limit = <limit>
    And param nobelPrizeYear = <nobelPrizeYear>
    And param yearTo = <yearTo>
    And param nobelPrizeCategory = <nobelPrizeCategory>
    When method GET
    Then status 200
    And match response.nobelPrizes == '#[]'
    And match response.nobelPrizes[*].awardYear == '#number'
    And match response.nobelPrizes[*].category.en == '#string'

    Examples:
      | offset | limit | nobelPrizeYear | yearTo | nobelPrizeCategory    |
      | [1]    | [10]  | [2020]         | [2021] | ['phy']               |
      | [2]    | [5]   | [2019]         | [2022] | ['che']               |

  Scenario: GET Nobel Prizes with invalid yearTo parameter
    Given path '2.1/nobelPrizes'
    And param nobelPrizeYear = 2020
    And param yearTo = 1899
    When method GET
    Then assert responseStatus != 200
    """
    And match response.error == {
      "code": '400',
      "message": '#string'
    }
    """

  Scenario: GET Nobel Prizes with nonexistent category
    Given path '2.1/nobelPrizes'
    And param nobelPrizeCategory = 'xyz'
    When method GET
    Then status 404
    """
    And match response.error == {
      "code": '404',
      "message": '#string'
    }
    """

  Scenario: GET Nobel Prizes with malformed offset parameter
    Given path '2.1/nobelPrizes'
    And param offset = 'abc'
    When method GET
    Then assert responseStatus != 200
    """
    And match response.error == {
      "code": '422',
      "message": '#string'
    }
    """
