# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=9818bf6b39
# 
# 

# ********RoostGPT********
Feature: Nobel Prize API Feature Tests

  Background:
    * def baseURL = karate.properties['NOBEL_PRIZE_MASTER_DATA_BASE_URL'] || karate.properties['API_HOST']
    * url baseURL
    * configure report = true
    * header Accept = 'application/json'

  Scenario Outline: Validate success response for Nobel Prize details
    Given path '2.1/nobelPrize/<category>/<year>'
    When method GET
    Then status 200
    And match response.nobelPrize.awardYear == ##number
    And match response.nobelPrize.category.en == ##string
    And match response.nobelPrize.category.se == '##string'
    And match response.nobelPrize.category.false == '##string'
    And match response.nobelPrize.categoryFullName.en == '##string'
    And match response.nobelPrize.categoryFullName.se == '##string'
    And match response.nobelPrize.categoryFullName.false == '##string'
    And match response.nobelPrize.dateAwarded == '##string'
    And match response.nobelPrize.prizeAmount == ##number
    And match response.nobelPrize.prizeAmountAdjusted == ##number
    And match response.nobelPrize.laureates == ARROf`.***[])
