# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_get for http method type GET 
# RoostTestHash=9f2a876166
# 
# 

# ********RoostGPT********
Feature: Get Country by ID
  Validate the endpoints for retrieving country information by ID with various scenarios

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase
    * header Accept = 'application/json'
    * header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    * header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'

  Scenario: Get country by valid ID
    Given path 'country', 32
    When method GET
    Then status 200
    And match response.status == 'success'
    And match response.message == 'Data fetched successfully'
    And match response.data.country.id == 32
    And match response.data.country.name == '#? _ == null || typeof _ == "string"'
    And match response.data.country.code == 'USA'
    And match response.data.country.default_currency == 'USD'
    And match response.data.country.is_active == 1
    And match response.data.country.app_id == 62
    And match response.data.country.customer_id == 48
    And match response.data.country.created_by == 0
    And match response.data.country.updated_by == 0
    And match response.data.country.created_at == '#string'
    And match response.data.country.updated_at == '#string'
    And match response.data.country.currencies == '#[]'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

  Scenario Outline: Get country by invalid ID
    Given path 'country', <id>
    When method GET
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | id  |
      | 999 |
      |  -1 |
      |   0 |

  Scenario Outline: Missing required headers
    * configure headers = {}
    Given path 'country', <id>
    When method GET
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | id |
      | 32 |

  Scenario Outline: Valid request without app-identifier
    * header customer-secret-key = '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe'
    Given path 'country', <id>
    When method GET
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | id |
      | 32 |

  Scenario Outline: Valid request without customer-secret-key
    * header app-identifier = 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d'
    Given path 'country', <id>
    When method GET
    Then status != 200
    And match response.error.code == '#number'
    And match response.error.message == '#string'

    Examples:
      | id |
      | 32 |
