# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Azure Open AI and AI Model roostgpt-4-32k
# 
# Feature file generated for /country/{id}_delete for http method type DELETE 
# RoostTestHash=5c040001f7
# 
# 

# ********RoostGPT********
Feature: Delete Country by ID API

  Background:
    * def urlBase = karate.properties['URL_BASE']
    * url urlBase

  Scenario Outline: Delete a country by ID successfully
    Given path 'country', <id>
    And headers { 'Accept': 'application/json', 'app-identifier': '<appIdentifier>', 'customer-secret-key': '<customerSecretKey>' }
    When method DELETE
    Then status 200
    And match response == '#object'
    And match response.status == '##string'
    And match response.message == '##string'
    And match response.error_info == '#? _ == null || typeof _ == "string"'

    Examples:
      | read('country_id_delete.csv') |

  Scenario: Attempt to delete a country with invalid ID
    Given path 'country', 99999
    And headers { 'Accept': 'application/json', 'app-identifier': 'd645d2b40811f5672c93794d8622da45588f32cdb2ed85336475bf479e5d', 'customer-secret-key': '12546580645c21b8a3529680f455f715b6b6829da8976bdfd2e9d51181fe' }
    When method DELETE
    Then assert responseStatus != 200
