// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type Open AI and AI Model gpt-3.5-turbo

ROOST_METHOD_HASH=listen_de605ac0dc
ROOST_METHOD_SIG_HASH=listen_7c68ad3120


*/

// ********RoostGPT********
import { app } from '../../examples/game/game';

describe('app.listen', () => {
  test('should log the server listening message with correct port', () => {
    const consoleSpy = jest.spyOn(console, 'log');
    const port = 3000;
    app.listen(port, () => {
      expect(consoleSpy).toHaveBeenCalledWith(`Server is listening at http://localhost:${port}`);
    });
  });

  test('should throw an error if port is not provided', () => {
    const consoleSpy = jest.spyOn(console, 'log');
    expect(() => {
      app.listen();
    }).toThrow();
    expect(consoleSpy).not.toHaveBeenCalledWith(expect.any(String));
  });
});
