// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type Open AI and AI Model gpt-3.5-turbo

ROOST_METHOD_HASH=onCallbackQuery_fb422e7f52
ROOST_METHOD_SIG_HASH=onCallbackQuery_7162a5be60


*/

// ********RoostGPT********
import bot from '../examples/polling';

describe('bot.on callback_query', () => {
  let callbackQuery = {
    data: 'edit',
    message: {
      chat: {
        id: 123
      },
      message_id: 456
    }
  };

  test('should edit message text when action is "edit"', () => {
    const expectedText = 'Edited Text';
    const expectedOpts = {
      chat_id: 123,
      message_id: 456
    };

    bot.on('callback_query', callbackQuery);
    
    expect(bot.editMessageText).toHaveBeenCalledWith(expectedText, expectedOpts);
  });

  test('should not edit message text for unknown action', () => {
    callbackQuery.data = 'unknown';
    
    bot.on('callback_query', callbackQuery);
    
    expect(bot.editMessageText).not.toHaveBeenCalled();
  });
});
