// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type Open AI and AI Model gpt-3.5-turbo

ROOST_METHOD_HASH=onEchoText_8a2e43fc98
ROOST_METHOD_SIG_HASH=onEchoText_8fbbfa8592


*/

// ********RoostGPT********
import { onEchoText } from '../examples/polling';

describe('onEchoText function', () => {
  let bot;
  let msg;
  
  beforeEach(() => {
    bot = {
      sendMessage: jest.fn()
    };
    msg = {
      chat: {
        id: 123
      }
    };
  });

  test('should echo the message correctly', () => {
    const match = ['/echo hello', 'hello'];
    onEchoText(msg, match);
    expect(bot.sendMessage).toHaveBeenCalledWith(123, 'hello');
  });

  test('should handle empty message', () => {
    const match = ['/echo', ''];
    onEchoText(msg, match);
    expect(bot.sendMessage).toHaveBeenCalledWith(123, '');
  });
});
