// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type Open AI and AI Model gpt-3.5-turbo

ROOST_METHOD_HASH=onEditableText_03ca139d60
ROOST_METHOD_SIG_HASH=onEditableText_1f461dd768


*/

// ********RoostGPT********
import { onEditableText } from '../examples/polling';

describe('onEditableText', () => {
  let mockBot;
  let mockMsg;

  beforeEach(() => {
    mockBot = {
      sendMessage: jest.fn()
    };
    mockMsg = {
      from: {
        id: 123
      }
    };
  });

  test('should send message with original text when /editable command is received', () => {
    onEditableText(mockBot, mockMsg);
    const expectedOpts = {
      reply_markup: {
        inline_keyboard: [[{
          text: 'Edit Text',
          callback_data: 'edit'
        }]]
      }
    };
    expect(mockBot.sendMessage).toHaveBeenCalledWith(123, 'Original Text', expectedOpts);
  });

  test('should not send message if msg.from is not defined', () => {
    const invalidMsg = {};
    onEditableText(mockBot, invalidMsg);
    expect(mockBot.sendMessage).not.toHaveBeenCalled();
  });
});
