// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type Open AI and AI Model gpt-3.5-turbo

ROOST_METHOD_HASH=onLoveText_1c32f744a2
ROOST_METHOD_SIG_HASH=onLoveText_fb28967bde


*/

// ********RoostGPT********
import { onLoveText } from '../examples/polling';

describe('onLoveText function', () => {
  let msg;

  beforeEach(() => {
    msg = {
      chat: { id: 123 },
      message_id: 456,
    };
  });

  test('should send a message asking "Do you love me?" with reply options', () => {
    const bot = {
      sendMessage: jest.fn(),
    };

    onLoveText(bot, msg);

    const expectedOpts = {
      reply_to_message_id: msg.message_id,
      reply_markup: JSON.stringify({
        keyboard: [['Yes, you are the bot of my life ❤'], ['No, sorry there is another one...']]
      })
    };

    expect(bot.sendMessage).toHaveBeenCalledWith(msg.chat.id, 'Do you love me?', expectedOpts);
  });

  test('should not send a message if bot is not provided', () => {
    const bot = undefined;

    expect(() => onLoveText(bot, msg)).toThrow();
  });
});
