// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type Open AI and AI Model gpt-3.5-turbo

ROOST_METHOD_HASH=onMessage_991085522b
ROOST_METHOD_SIG_HASH=onMessage_d3cc9ec5c0


*/

// ********RoostGPT********
import { bot } from '../../examples/webhook/openshift2';

describe('Bot on message event', () => {
  test('Should send message "I am alive on OpenShift!" when receiving a message', () => {
    const mockChatId = 12345;
    const sendMessageMock = jest.fn();
    bot.sendMessage = sendMessageMock;

    bot.emit('message', { chat: { id: mockChatId } });

    expect(sendMessageMock).toHaveBeenCalledWith(mockChatId, 'I am alive on OpenShift!');
  });

  test('Should not send message if chat id is missing', () => {
    const sendMessageMock = jest.fn();
    bot.sendMessage = sendMessageMock;

    bot.emit('message', { chat: {} });

    expect(sendMessageMock).not.toHaveBeenCalled();
  });
});
