// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type Open AI and AI Model gpt-3.5-turbo

ROOST_METHOD_HASH=onPhotoText_862f020116
ROOST_METHOD_SIG_HASH=onPhotoText_3ca866637b


*/

// ********RoostGPT********
import { onPhotoText } from '../examples/polling';

describe('onPhotoText function', () => {
  test('should send a photo with caption when /photo command is received', () => {
    const msg = { chat: { id: 123 } };
    const bot = {
      sendPhoto: jest.fn(),
    };
    
    onPhotoText(bot, msg);
    
    expect(bot.sendPhoto).toHaveBeenCalledWith(123, `${__dirname}/../test/data/photo.gif`, {
      caption: "I'm a bot!"
    });
  });

  test('should not send a photo if chat id is missing', () => {
    const msg = { chat: {} };
    const bot = {
      sendPhoto: jest.fn(),
    };
    
    onPhotoText(bot, msg);
    
    expect(bot.sendPhoto).not.toHaveBeenCalled();
  });
});
