// ********RoostGPT********
/*
Test generated by RoostGPT for test java-customannotation-test using AI Type Open AI and AI Model gpt-3.5-turbo

ROOST_METHOD_HASH=stringify_d5fe20fec0
ROOST_METHOD_SIG_HASH=stringify_15b78a056f


*/

// ********RoostGPT********
// __tests__/telegram.test.js

const { stringify } = require('../src/telegram');

describe('stringify function', () => {
  test('should return the same string if input is already a string', () => {
    const result = stringify('test');
    expect(result).toBe('test');
  });

  test('should return a JSON string if input is not a string', () => {
    const result = stringify({ key: 'value' });
    expect(result).toBe('{"key":"value"}');
  });

  test('should return a JSON string even if input is a number', () => {
    const result = stringify(123);
    expect(result).toBe('123');
  });

  test('should return a JSON string for an array input', () => {
    const result = stringify([1, 2, 3]);
    expect(result).toBe('[1,2,3]');
  });

  test('should return a JSON string for a boolean input', () => {
    const result = stringify(true);
    expect(result).toBe('true');
  });
});
